/**
 *DriveAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/09/2016
 */

'use strict';
angular.module('DriveAPILib',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        BASEURI : "https://www.googleapis.com/drive/v2",

        //The OAuth 2.0 access token to be set before API calls
        //TODO: Replace the oAuthAccessToken with an appropriate value
        oAuthAccessToken : "731566467334-up2cbdg5nmoj1q3gusfj8n9ce1c4mmsg.apps.googleusercontent.com"

    };
});

